export const MEETINGS_FETCH_START = 'MEETINGS_FETCH_START';
export const MEETINGS_FETCH_FAILURE = 'MEETINGS_FETCH_FAILURE';
export const MEETINGS_FETCH_SUCCESS = 'MEETINGS_FETCH_SUCCESS';

export const MEETING_CREATE_START = 'MEETING_CREATE_START';
export const MEETING_CREATE_FAILURE = 'MEETING_CREATE_FAILURE';
export const MEETING_CREATE_SUCCESS = 'MEETING_CREATE_SUCCESS';

export const CREATE_UI_RESET = 'CREATE_UI_RESET';

export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const REMOVE_PARTICIPANT = 'REMOVE_PARTICIPANT';

export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE';
export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE';

export const LOCAL_STREAM_STARTED = 'LOCAL_STREAM_STARTED';
