export const MEETING_FETCH_START = 'MEETING_FETCH_START';
export const MEETING_FETCH_FAILURE = 'MEETING_FETCH_FAILURE';
export const MEETING_FETCH_SUCCESS = 'MEETING_FETCH_SUCCESS';

export const MEETING_CREATE_START = 'MEETING_CREATE_START';
export const MEETING_CREATE_FAILURE = 'MEETING_CREATE_FAILURE';
export const MEETING_CREATE_SUCCESS = 'MEETING_CREATE_SUCCESS';

export const CREATE_UI_RESET = 'CREATE_UI_RESET';

export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const REMOVE_PARTICIPANT = 'REMOVE_PARTICIPANT';

export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE';
export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE';
export const FILE_UPLOADED = 'FILE_UPLOADED';
export const ADD_UPLOADED_FILE = 'ADD_UPLOADED_FILE';

export const TOGGLE_AUDIO = 'TOGGLE_AUDIO';
export const TOGGLE_VIDEO = 'TOGGLE_VIDEO';
export const TOGGLE_SCREENSHARE = 'TOGGLE_SCREENSHARE';
