export const MEETINGS_FETCH_START = 'MEETINGS_FETCH_START';
export const MEETINGS_FETCH_FAILURE = 'MEETINGS_FETCH_FAILURE';
export const MEETINGS_FETCH_SUCCESS = 'MEETINGS_FETCH_SUCCESS';

export const MEETING_CREATE_START = 'MEETING_CREATE_START';
export const MEETING_CREATE_FAILURE = 'MEETING_CREATE_FAILURE';
export const MEETING_CREATE_SUCCESS = 'MEETING_CREATE_SUCCESS';
